spring:
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  database:
    driverClassName: org.postgresql.Driver
  datasource:
    url: jdbc:postgresql://localhost:5432/jalmew_auth
    username: postgres
    password: password
    initial-size: 5
    max-active: 100
    max-idle: 5
    test-on-borrow: true
    test-while-idle: true
    test-on-return: true
    min-idle: 2
    validation-query: select 1

liquibase:
  change-log: classpath:db-changelog.xml

server:
  context-path: /uaa
  port: 5000

logging:
  level:
    org.springframework.security: DEBUG