server:
  port: 4000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    auth-service:
      path: /uaa/**
      clientId: auth-service
#      url: http://localhost:5000
      stripPrefix: false

    wordbook-service:
      path: /wordbook/**
      clientId: wordbook-service
      stripPrefix: false

    word-service:
      path: /word/**
      clientId: word-service
      stripPrefix: false

    ytranslate-service:
      path: /yTranslate/**
      clientId: ytranslate-service
      stripPrefix: false

    learn-service:
      path: /learn/**
      clientId: learn-service
      stripPrefix: false

