server:
  port: 9020

logging:
  level:
    org.springframework: TRACE
    org.hibernate: TRACE

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:5000/uaa/users/current
    client:
      clientId: word-service
      clientSecret: password
      accessTokenUri: http://localhost:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      host: localhost
      username: user
      password: password
      database: jalmew_word
      port: 27017

